name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: Compile Swift Code
      run: swift build
    - name: Test Swift Code
      run: swift test
