name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Compile Swift Code
      run: |
        swiftc impaste.swift
