name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: Build Release Executable
      run: swift build -c release
    - name: Create A Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
    - name: Upload Release Executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./.build/arm64-apple-macosx/release/pbimg
        asset_name: pbimg
        asset_content_type: application/octet-stream
